import argparse
import csv
from datetime import datetime
from pathlib import Path
import sys
from typing import Mapping


BACKEND_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_ROOT.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.models.simulation import (  # noqa: E402
    Boundary,
    DomainSettings,
    GeometryNode,
    GlobalSettings,
    Material,
    SimulationProject,
    Source,
)
from app.services.starfish_runner import StarfishRunResult, StarfishRunnerService  # noqa: E402
from app.services.xml_generator import XMLGeneratorService  # noqa: E402


def build_demo_project(
    iterations: int = 100,
    mdot: float = 1e-10,
    spwt: float = 1e8,
) -> SimulationProject:
    return SimulationProject(
        settings=GlobalSettings(
            iterations=iterations,
            time_step=1e-6,
            solver_type="none",
            max_cores=1,
        ),
        domain=DomainSettings(
            type="xy",
            mesh_name="mesh",
            origin=[0.0, 0.0],
            spacing=[0.01, 0.01],
            nodes=[21, 11],
        ),
        boundaries=[
            Boundary(
                name="inlet",
                type="virtual",
                # Starfish surface sources use boundary orientation; this order injects into the domain.
                nodes=[GeometryNode(x=0.0, y=0.1), GeometryNode(x=0.0, y=0.0)],
            ),
            Boundary(
                name="bottom_wall",
                type="solid",
                nodes=[GeometryNode(x=0.0, y=0.0), GeometryNode(x=0.2, y=0.0)],
            ),
            Boundary(
                name="top_wall",
                type="solid",
                nodes=[GeometryNode(x=0.0, y=0.1), GeometryNode(x=0.2, y=0.1)],
            ),
            Boundary(
                name="outlet",
                type="virtual",
                nodes=[GeometryNode(x=0.2, y=0.0), GeometryNode(x=0.2, y=0.1)],
            ),
        ],
        materials=[
            Material(name="O+", type="kinetic", molwt=15.999, charge=1, spwt=spwt),
            Material(name="wall", type="solid", density=8000),
        ],
        sources=[
            Source(
                name="ion_beam",
                type="uniform",
                material="O+",
                boundary="inlet",
                mdot=mdot,
                temperature=300,
                v_drift=1000,
            )
        ],
    )


def default_output_dir() -> Path:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return REPO_ROOT / "starfish_runs" / f"ezxml_demo_{stamp}"


def read_stats(stats_file: Path) -> tuple[list[str], list[dict[str, str]]]:
    if not stats_file.exists():
        return [], []
    with stats_file.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        return list(reader.fieldnames or []), list(reader)


def important_log_lines(log_file: Path) -> list[str]:
    if not log_file.exists():
        return []

    interesting_prefixes = (
        "Loading ",
        "Processing <",
        "Domain type:",
        "Added ",
        "> nodes",
        "> origin",
        "> spacing",
        ">dt:",
        ">max_it:",
        "Starting main loop",
        "it:",
        "Source Summary:",
        "ion_beam:",
        "Done!",
        "WARNING:",
        "ERROR:",
    )
    lines = log_file.read_text(encoding="utf-8", errors="replace").splitlines()
    return [line for line in lines if line.strip().startswith(interesting_prefixes)]


def result_summary(
    output_dir: Path,
    xml_files: Mapping[str, str],
    run_result: StarfishRunResult,
) -> str:
    files = sorted(path for path in output_dir.iterdir() if path.is_file())
    headers, rows = read_stats(output_dir / "starfish_stats.csv")
    last_row = rows[-1] if rows else {}
    log_lines = important_log_lines(output_dir / "starfish.log")

    summary: list[str] = [
        "# ezxml -> Starfish Demo Result",
        "",
        f"- Output directory: `{output_dir}`",
        f"- Starfish exit code: `{run_result.returncode}`",
        f"- Runner status: `{'PASS' if run_result.ok else 'FAIL'}`",
        f"- Elapsed seconds: `{run_result.elapsed_seconds:.3f}`",
        f"- XML files generated by ezxml: `{', '.join(sorted(xml_files))}`",
        "",
        "## Generated Files",
        "",
        "| File | Size bytes |",
        "| --- | ---: |",
    ]

    for path in files:
        summary.append(f"| {path.name} | {path.stat().st_size} |")

    summary.extend(
        [
            "",
            "## Statistics",
            "",
            f"- Stats columns: `{len(headers)}`",
            f"- Stats rows: `{len(rows)}`",
        ]
    )

    if last_row:
        selected_keys = [
            "it",
            "time",
            "mp.O+",
            "mass.O+",
            "source.ion_beam (kg/s)",
            "flux.inlet.O+ (#/m^2/s)",
        ]
        summary.extend(["", "| Field | Final value |", "| --- | ---: |"])
        for key in selected_keys:
            if key in last_row:
                summary.append(f"| {key} | {last_row[key]} |")

    if log_lines:
        summary.extend(["", "## Log Highlights", ""])
        for line in log_lines[-30:]:
            summary.append(f"- `{line}`")

    if run_result.output:
        summary.extend(["", "## Console Tail", ""])
        for line in run_result.output.splitlines()[-20:]:
            summary.append(f"- `{line}`")

    return "\n".join(summary) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate ezxml XML files, run Starfish, and summarize results.")
    parser.add_argument("--output-dir", type=Path, default=None, help="Directory for XML and Starfish result files.")
    parser.add_argument("--timeout", type=int, default=30, help="Starfish timeout in seconds.")
    parser.add_argument("--iterations", type=int, default=100, help="Number of Starfish iterations.")
    parser.add_argument("--mdot", type=float, default=1e-10, help="Uniform source mass flow rate.")
    parser.add_argument("--spwt", type=float, default=1e8, help="Kinetic material statistical weight.")
    args = parser.parse_args()

    output_dir = (args.output_dir or default_output_dir()).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    project = build_demo_project(iterations=args.iterations, mdot=args.mdot, spwt=args.spwt)
    xml_files = XMLGeneratorService().generate_xml_files(project)
    runner = StarfishRunnerService()

    print(f"Generating ezxml XML cluster into: {output_dir}")
    result = runner.run_xml_files(xml_files, timeout=args.timeout, work_dir=output_dir)

    summary = result_summary(output_dir, xml_files, result)
    summary_file = output_dir / "result_summary.md"
    summary_file.write_text(summary, encoding="utf-8")

    print(summary)
    print(f"Summary file: {summary_file}")
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
